parameters:
    twitter.consumer_key: 'wEX8Alm9tQuWnRsB4JfCQd8mO'
    twitter.consumer_secret: 'hpm51WZZXEGkOjgv6BMVqMUlEEguXbLLdiL2mn4rQAULXg2p4j'
    twitter.token: '1300030753-yGhUHE8VctwCNN8PJa9JtZG7j1I1VBPzXFWaekt'
    twitter.token_secret: 'zo3FCBJEmMaFR8IYrKk2qQmKsjAyLdzkQbpbDVrCJ8S7b'
    gcm_ttl: ''
    link_placeholder: ''
    max_pushes_per_hour: ''

services:
    hayzem_twitter_stream.service.twitter-stream-service:
        class: Hayzem\TwitterStreamBundle\Service\TwitterStreamService

    hayzem_twitter_stream.command.twitter-track-command:
        class: Hayzem\TwitterStreamBundle\Command\TwitterTrackCommand
        arguments:
            - "@hayzem_twitter_stream.twitter_stream_client"
            - "@monolog.logger"
        tags:
            - { name: console.command }

    hayzem_twitter_stream.twitter_stream_client:
        class: GuzzleHttp\Client
        factory: [Hayzem\TwitterStreamBundle\DependencyInjection\GuzzleClientFactory, get]
        arguments:
            -
                base_uri: "https://stream.twitter.com/1.1/"
                auth: oauth
            - "@hayzem_twitter_stream.twitter_oauth"
            - "@monolog.logger"
            - "@hayzem_twitter_stream.service.twitter-stream-service"

    hayzem_twitter_stream.twitter_oauth:
        class: GuzzleHttp\Subscriber\Oauth\Oauth1
        arguments:
            -
                consumer_key: "%twitter.consumer_key%"
                consumer_secret: "%twitter.consumer_secret%"
                token: "%twitter.token%"
                token_secret: "%twitter.token_secret%"

    hayzem_twitter_stream.event.track.control:
        class: Hayzem\TwitterStreamBundle\EventListener\TrackControlListener
        arguments: ["%kernel.root_dir%", "@monolog.logger"]
        tags:
            - {name: kernel.event_listener, event:twitter_stream.event.track.control.start, method:startTrackHandler}
            - {name: kernel.event_listener, event:twitter_stream.event.track.control.restart, method:restartTrackHandler}
            - {name: kernel.event_listener, event:twitter_stream.event.track.control.stop, method:stopTrackHandler}

